export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN';
export const CLEAR_AUTH_TOKEN = 'CLEAR_AUTH_TOKEN';
export const SET_WORKOUT_PLAN = 'SET_WORKOUT_PLAN';
export const CLEAR_WORKOUT_PLAN = 'CLEAR_WORKOUT_PLAN';
export const SET_NUTRITION_PLAN = 'SET_NUTRITION_PLAN';


